apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: reactjs-hpa
  namespace: btg-boilerplate-prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: reactjs # Must match your Deployment's name
  minReplicas: 3 # The min number of replicas your application should run
  maxReplicas: 5 # The max number of replicas your application can scale up to (You can change this acording to your application's load needed)
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80 # Target CPU utilization (percentage) across all pods
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300 # Time to scale down
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60
        - type: Percent
          value: 100
          periodSeconds: 60
    scaleUp:
      policies:
        - type: Pods
          value: 4
          periodSeconds: 60
        - type: Percent
          value: 100
          periodSeconds: 60
      stabilizationWindowSeconds: 0
