# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - dev # change to your branch

variables:
  containerRegistryConection: 'app-nonprod-registry'
  deploymentFileName: 'visionapiservicedev-deployment.yaml'
  workerDeploymentFileName: 'vision-worker-deployment.yaml'
  imageName: 'btg-labware-vision-api-service'
  workerImageName: 'btg-labware-vision-worker'
  environment: 'dev'
  pool: 'GCP-NONPRD-POOL'
  GCP_PROJECT_ID: 'app-nonprod-project'
  GCP_REPO: 'app-nonprod-ar'
  updateK8sScriptFile: 'updateK8smanifest.sh'
  containerImageRepository: 'asia-southeast1-docker.pkg.dev/$(GCP_PROJECT_ID)/$(GCP_REPO)/$(imageName)' #dev
  workerContainerImageRepository: 'asia-southeast1-docker.pkg.dev/$(GCP_PROJECT_ID)/$(GCP_REPO)/$(workerImageName)' #dev worker
  k8sManifestRepoUrl: 'git@ssh.dev.azure.com:v3/betagro-dev/Labware-hemagglutinatio_inhibition_test_automation/Manifest' # add your k8s  manifest repository here (SSH approach only)

# CI
stages:
  # Stage: Build (Interacting with GCP starts here)
  - stage: Build
    displayName: Build stage
    condition: succeeded()
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: |
              echo $sourceVersion
              commitHash=${sourceVersion:0:8}
              echo $commitHash
              echo "##vso[task.setvariable variable=commitHash]$commitHash"
            env: { sourceVersion: $(Build.SourceVersion) }
            displayName: Git Hash 8-digit

          # Build and push API image
          - task: Docker@2
            displayName: 'Build API image'
            inputs:
              containerRegistry: '$(containerRegistryConection)'
              repository: '$(GCP_PROJECT_ID)/$(GCP_REPO)/$(imageName)'
              command: 'build'
              Dockerfile: '**/Dockerfile'
              tags: |
                dev-latest
                dev-$(Build.SourceVersion)
              arguments: '--build-arg="GIT_COMMIT_SHA=$(commitHash)"'

          - task: Docker@2
            displayName: 'Push API image (latest)'
            inputs:
              containerRegistry: '$(containerRegistryConection)'
              repository: '$(GCP_PROJECT_ID)/$(GCP_REPO)/$(imageName)'
              command: 'push'
              tags: dev-latest

          - task: Docker@2
            displayName: 'Push API image (version)'
            inputs:
              containerRegistry: '$(containerRegistryConection)'
              repository: '$(GCP_PROJECT_ID)/$(GCP_REPO)/$(imageName)'
              command: 'push'
              tags: dev-$(Build.SourceVersion)

          # Build and push Worker image
          - task: Docker@2
            displayName: 'Build Worker image'
            inputs:
              containerRegistry: '$(containerRegistryConection)'
              repository: '$(GCP_PROJECT_ID)/$(GCP_REPO)/$(workerImageName)'
              command: 'build'
              Dockerfile: '**/Dockerfile.worker'
              tags: |
                dev-latest
                dev-$(Build.SourceVersion)
              arguments: '--build-arg="GIT_COMMIT_SHA=$(commitHash)"'

          - task: Docker@2
            displayName: 'Push Worker image (latest)'
            inputs:
              containerRegistry: '$(containerRegistryConection)'
              repository: '$(GCP_PROJECT_ID)/$(GCP_REPO)/$(workerImageName)'
              command: 'push'
              tags: dev-latest

          - task: Docker@2
            displayName: 'Push Worker image (version)'
            inputs:
              containerRegistry: '$(containerRegistryConection)'
              repository: '$(GCP_PROJECT_ID)/$(GCP_REPO)/$(workerImageName)'
              command: 'push'
              tags: dev-$(Build.SourceVersion)

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifact: drop'
  - stage: Update
    displayName: Update K8s Manifests
    dependsOn: Build
    condition: succeeded()
    jobs:
      - job: UpdateManifests
        displayName: Update K8s Manifests
        pool:
          name: $(pool)
        steps:
          - checkout: self
            displayName: 'Checkout source code'
          
          # FIX: Add this step to fix line endings
          - task: Bash@3
            displayName: 'Fix Script Line Endings'
            inputs:
              targetType: 'inline'
              script: |
                echo "Fixing line endings in $(updateK8sScriptFile)..."
                # Remove Windows carriage returns
                sed -i 's/\r$//' $(System.DefaultWorkingDirectory)/$(updateK8sScriptFile)
                # Make script executable
                chmod +x $(System.DefaultWorkingDirectory)/$(updateK8sScriptFile)
                # Verify the fix
                echo "Verifying file..."
                file $(System.DefaultWorkingDirectory)/$(updateK8sScriptFile)
                echo "First 3 lines:"
                head -3 $(System.DefaultWorkingDirectory)/$(updateK8sScriptFile)
              workingDirectory: '$(System.DefaultWorkingDirectory)'
          
          - task: Bash@3
            displayName: 'Update API K8s Manifest'
            inputs:
              targetType: 'filePath'
              filePath: '$(System.DefaultWorkingDirectory)/$(updateK8sScriptFile)'
              arguments: '$(environment) dev-$(Build.SourceVersion) $(containerImageRepository) $(k8sManifestRepoUrl) $(deploymentFileName)'
              workingDirectory: '$(System.DefaultWorkingDirectory)'
              # failOnStderr: true
            env:
              ENVIRONMENT: $(environment)
              IMAGE_TAG: dev-$(Build.SourceVersion)
              CONTAINER_REGISTRY: $(containerImageRepository)
              K8S_MANIFEST_REPO: $(k8sManifestRepoUrl)
              DEPLOYMENT_FILE_NAME: $(deploymentFileName)

          - task: Bash@3
            displayName: 'Update Worker K8s Manifest'
            inputs:
              targetType: 'filePath'
              filePath: '$(System.DefaultWorkingDirectory)/$(updateK8sScriptFile)'
              arguments: '$(environment) dev-$(Build.SourceVersion) $(workerContainerImageRepository) $(k8sManifestRepoUrl) $(workerDeploymentFileName)'
              workingDirectory: '$(System.DefaultWorkingDirectory)'
              # failOnStderr: true
            env:
              ENVIRONMENT: $(environment)
              IMAGE_TAG: dev-$(Build.SourceVersion)
              CONTAINER_REGISTRY: $(workerContainerImageRepository)
              K8S_MANIFEST_REPO: $(k8sManifestRepoUrl)
              DEPLOYMENT_FILE_NAME: $(workerDeploymentFileName)